version: '2.1'
services:
  mysql:
    image: mysql:5.7.19
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - "~/data/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD:
